# Étape 1 : build du frontend avec Node
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Étape 2 : servir les fichiers statiques avec Nginx
FROM nginx:alpine

# Copier le build Vite
COPY --from=build /app/dist /usr/share/nginx/html

# (Optionnel) config Nginx custom, sinon il sert index.html par défaut
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]