services:
  # ---------- Base de données MySQL ----------
  db:
    image: mysql:8.0
    container_name: isam-dash-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: isam_dash
      MYSQL_USER: pfe_user
      MYSQL_PASSWORD: pfe_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "pfe_user", "-ppfe_pass"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  # ---------- Logs-service ----------
  logs-service:
    image: amir20/dozzle:latest
    container_name: logs-service-container
    ports:
      - "8010:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  # ---------- Auth-service ----------
  auth-service:
    build: ./auth-service
    container_name: auth-service-container
    ports:
      - "9000:9000"
    environment:
      - DB_URL=mysql+pymysql://pfe_user:pfe_pass@db:3306/isam_dash
      - JWT_SECRET_KEY=GfN4v8jKQyG8p0LpjJ7dYQH9q2sLAX7m0pW3sZrTn9uN3xCyBh3FgTzW9Lk5QsM2
      - JWT_ALGORITHM=HS256
    depends_on:
      db:
<<<<<<< HEAD
        condition: service_healthy   # ← waits for MySQL to be truly ready
=======
        condition: service_healthy
>>>>>>> fd10cbc8934102393ea226c2ab4e29b2e1a71553
    restart: on-failure

  # ---------- ISAM-service ----------
  isam-service:
    build: ./isam-service
    container_name: isam-service-container
    ports:
      - "8001:8001"
    environment:
      - DB_URL=mysql+pymysql://pfe_user:pfe_pass@db:3306/isam_dash
      - AUTH_SERVICE_URL=http://auth-service:9000
      - JWT_SECRET_KEY=GfN4v8jKQyG8p0LpjJ7dYQH9q2sLAX7m0pW3sZrTn9uN3xCyBh3FgTzW9Lk5QsM2
      - JWT_ALGORITHM=HS256
    depends_on:
      db:
<<<<<<< HEAD
        condition: service_healthy   # ← waits for MySQL
      auth-service:
        condition: service_started   # ← waits for auth to start
=======
        condition: service_healthy
      auth-service:
        condition: service_started
>>>>>>> fd10cbc8934102393ea226c2ab4e29b2e1a71553
    restart: on-failure

  # ---------- Frontend ----------
  frontend:
<<<<<<< HEAD
      build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
          - VITE_AUTH_BASE_URL=http://10.255.25.77:9000
          - VITE_ISAM_BASE_URL=http://10.255.25.77:8001
      container_name: isam-frontend-container
      ports:
        - "5173:80"
      depends_on:
        - auth-service
        - isam-service
      restart: on-failure
=======
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_AUTH_BASE_URL=http://10.255.25.77:9000
        - VITE_ISAM_BASE_URL=http://10.255.25.77:8001
    container_name: isam-frontend-container
    ports:
      - "5173:80"
    depends_on:
      - auth-service
      - isam-service
    restart: on-failure
>>>>>>> fd10cbc8934102393ea226c2ab4e29b2e1a71553

volumes:
  db_data: